### ISSUE TITLE
Generating input file automatically?

### ISSUE THREAD

**Issue by joshuak94** [vishakad/chipulate#3]
Hello. Firstly, thanks for the great tool! I've been struggling to find a ChIP-seq simulation tool.

I was able to run the basic and fastq examples fine. However, I would now like to simulate a much larger dataset, with many binding sites across several chromosomes.

I was wondering if this was something that Chipulate can handle. I can't imagine manually creating such a file, and was wondering if a script or something existed that would create this for me.

Thank you!

**Comment by vishakad** [comment]
So you could use the bedtools random command (https://bedtools.readthedocs.io/en/latest/content/tools/random.html) to generate a set of intervals, each of fixed length. You could then run a script that changes the length of each interval by a random amount. 

Chipulate should be able to handle larger inputs. The main issue is really one of memory. You could perhaps start with 100,000 binding sites and see how long the simulation takes.
